name: auth_basic
version: 0.4.0
description: Basic authentication example with jaguar, jaguar_auth and jaguar_session
dependencies:
  jaguar: ^0.6.16               # Provides routing
  jaguar_auth: ^0.12.0          # Server-side authentication
  jaguar_json: ^0.2.0           # Server-side JSON utilities
  jaguar_serializer: ^0.5.0     # Serialization library
  jaguar_client: ^0.2.0         # http client library
  ulid: ^1.0.0
