name: server
version: 0.4.0
description: Authentication example with jaguar and jaguar_auth
dependencies:
  jaguar: ^1.3.1                    # Provides routing
  jaguar_auth: ^1.3.1               # Server-side authentication
  jaguar_serializer: ^1.0.0-dev5    # Serialization library
  jaguar_serializer_mongo: ^1.0.0-dev5
  ulid: ^1.0.0
  jaguar_dev_proxy: ^1.2.6
  jaguar_reflect: ^1.2.6
  common:
    path: ../common

dev_dependencies:
  build_runner: ^0.7.0
  jaguar_serializer_cli: ^1.0.0-dev1
